version: '3.7'

services:
  postgres:
    image: postgres
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  admin-service:
    image: "lfp:0.1.7"
    container_name: admin-service
    ports:
      - "8081:8081"
    environment:
      - DATASOURCE_PASSWORD=postgre
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/jwtappbase
      - DATASOURCE_USERNAME=postgres
      - JWT_EXPIRED=1000000
      - JWT_SECRET=amogus
      - SERVER_PORT=8081
      - TOPIC_NAME=email-topic
      - KAFKA_HOST=kafka:9092
    depends_on:
      - postgres
      - kafka

#  email-service:
#    image: "lfpe:0.0.4"
#    container_name: email-service
#    ports:
#      - "8080:8082"
#    environment:
#      - KAFKA_HOST=kafka:9092
#      - TOPIC_NAME=email-topic
#      - MAIL_USERNAME=noilzep@gmail.com
#      - MAIL_PASSWORD=gish syjq zesb dfsy
#      - SERVER_PORT=8082
#    depends_on:
#      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:9093
      # setted as 3 by default, failing with single instance running
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zookeeper

volumes:
  postgres-data:
  kafka-data: