version: '3.7'

services:
  admin-service:
    image: "asayke/lfp:light-0.0.1"
    container_name: admin-service-light
    ports:
      - "8081:8081"
    environment:
      JWT_EXPIRED: 1000000
      JWT_SECRET: amogus
      SERVER_PORT: 8081
      TOPIC_NAME: email-topic
      KAFKA_HOST: kafka:29092
