server:
  port: ${SERVER_PORT}

spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer
    topic:
      name: ${TOPIC_NAME}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    url: ${DATASOURCE_URL}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false
jwt:
  token:
    secret: ${JWT_SECRET}
    expired: ${JWT_EXPIRED}